// Generated by CoffeeScript 1.6.2
(function() {
  var colors, draw, drawChart, formatDate, getBotStats, makeData, makeLabels, pad, period, stats;

  stats = {};

  period = null;

  jQuery(function() {
    var $;

    $ = jQuery;
    return draw();
  });

  $(window).bind("hashchange", function() {
    return draw();
  });

  draw = function() {
    period = $.bbq.getState("period") || "hour";
    return $.getJSON("bots.json", function(bots) {
      var botNames, name;

      botNames = (function() {
        var _results;

        _results = [];
        for (name in bots) {
          _results.push(name);
        }
        return _results;
      })();
      botNames = botNames.filter(function(name) {
        return bots[name] !== null;
      });
      async.map(botNames, getBotStats, drawChart);
      $(".nav li").removeClass("active");
      return $("#period-" + period).addClass("active");
    });
  };

  getBotStats = function(name, callback) {
    var url;

    url = ("stats/" + name + "_") + period + ".json";
    return $.getJSON(url, function(stats, status, jqXHR) {
      stats.shift();
      stats.unshift(name);
      return callback(null, stats);
    });
  };

  drawChart = function(err, stats, selected) {
    var chart, ctx, data, dataset, legend, li, opts, _i, _len, _ref;

    ctx = $('#chart').get(0).getContext("2d");
    chart = new Chart(ctx);
    data = makeData(stats, selected);
    opts = {
      pointDot: false,
      datasetFill: false,
      scaleShowLabels: true,
      datasetStrokeWidth: 2,
      animation: false
    };
    chart.Line(data, opts);
    legend = $("#legend");
    legend.empty();
    _ref = data.datasets;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      dataset = _ref[_i];
      li = $('<li><a data-dataset="' + dataset.name + '" style="color: ' + dataset.strokeColor + '" href="http://wikidata.org/wiki/User:' + dataset.name + '">' + dataset.name + '</a></li>');
      legend.append(li);
    }
    return $("#legend a").hover(function(ev) {
      var newSelected;

      console.log($(ev.target).css('color'));
      newSelected = $(ev.target).data('dataset');
      if (newSelected !== selected) {
        return drawChart(err, stats, newSelected);
      }
    }, function(ev) {
      console.log(ev.type);
      $(ev.target).css('font-weight', 'normal');
      return drawChart(err, stats);
    });
  };

  makeData = function(stats, selected) {
    var color, data, datasets, hasData, i, labels, name, row, s, _i, _j, _len, _len1, _ref;

    datasets = [];
    console.log(selected);
    for (i = _i = 0, _len = stats.length; _i < _len; i = ++_i) {
      s = stats[i];
      name = s[0];
      labels = makeLabels(stats);
      color = colors[i];
      if (selected && selected !== name) {
        color = color.replace('0.7', '0.1');
      }
      data = [];
      hasData = false;
      _ref = s.slice(1);
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        row = _ref[_j];
        if (row[1] > 0) {
          hasData = true;
        }
        data.push(row[1]);
      }
      if (hasData) {
        datasets.push({
          name: name,
          strokeColor: color,
          data: data
        });
      }
    }
    return {
      labels: labels,
      datasets: datasets
    };
  };

  makeLabels = function(stats) {
    var count, d, labels, row, _i, _len, _ref;

    count = 0;
    labels = [];
    _ref = stats[1];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      row = _ref[_i];
      if (count % 7 === 0) {
        d = new Date(row[0] * 1000);
        labels.push(formatDate(d));
      } else {
        labels.push("");
      }
      count += 1;
    }
    return labels;
  };

  pad = function(n) {
    if (n < 10) {
      return '0' + n;
    } else {
      return n;
    }
  };

  formatDate = function(d) {
    return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate()) + ' ';
  };

  colors = ["rgba(103, 0, 31, 0.7)", "rgba(178, 24, 43, 0.7)", "rgba(214, 96, 77, 0.7)", "rgba(244, 165, 130, 0.7)", "rgba(209, 229, 240, 0.7)", "rgba(146, 197, 222, 0.7)", "rgba(67, 147, 195, 0.7)", "rgba(33, 102, 172, 0.7)", "rgba(5, 48, 97, 0.7)", "rgba(103, 0, 31, 0.7)", "rgba(178, 24, 43, 0.7)", "rgba(214, 96, 77, 0.7)", "rgba(244, 165, 130, 0.7)", "rgba(186, 186, 186, 0.7)", "rgba(135, 135, 135, 0.7)", "rgba(77, 77, 77, 0.7)", "rgba(26, 26, 26, 0.7)", "rgba(165, 0, 38, 0.7)", "rgba(215, 48, 39, 0.7)", "rgba(244, 109, 67, 0.7)", "rgba(253, 174, 97, 0.7)", "rgba(254, 224, 144, 0.7)", "rgba(171, 217, 233, 0.7)", "rgba(116, 173, 209, 0.7)", "rgba(69, 117, 180, 0.7)", "rgba(49, 54, 149, 0.7)", "rgba(165, 0, 38, 0.7)", "rgba(215, 48, 39, 0.7)", "rgba(244, 109, 67, 0.7)", "rgba(253, 174, 97, 0.7)", "rgba(254, 224, 139, 0.7)", "rgba(255, 255, 191, 0.7)", "rgba(217, 239, 139, 0.7)", "rgba(166, 217, 106, 0.7)", "rgba(102, 189, 99, 0.7)", "rgba(26, 152, 80, 0.7)", "rgba(0, 104, 55, 0.7)"];

}).call(this);
