// Generated by CoffeeScript 1.6.2
(function() {
  var colors, draw, drawChart, formatDate, getBotStats, makeData, makeLabels, pad, period, stats;

  stats = {};

  period = null;

  jQuery(function() {
    var $;

    $ = jQuery;
    return draw();
  });

  $(window).bind("hashchange", function() {
    return draw();
  });

  draw = function() {
    period = $.bbq.getState("period") || "hour";
    return $.getJSON("bots.json", function(bots) {
      var botNames, name;

      botNames = (function() {
        var _results;

        _results = [];
        for (name in bots) {
          _results.push(name);
        }
        return _results;
      })();
      async.map(botNames, getBotStats, drawChart);
      $(".nav li").removeClass("active");
      return $("#period-" + period).addClass("active");
    });
  };

  getBotStats = function(name, callback) {
    var url;

    url = ("stats/" + name + "_") + period + ".json";
    return $.getJSON(url, function(stats) {
      stats.shift();
      stats.unshift(name);
      return callback(null, stats);
    });
  };

  drawChart = function(err, stats) {
    var chart, ctx, data, dataset, legend, li, opts, _i, _len, _ref, _results;

    ctx = $('#chart').get(0).getContext("2d");
    chart = new Chart(ctx);
    data = makeData(stats);
    opts = {
      pointDot: false,
      datasetFill: false,
      scaleShowLabels: true,
      datasetStrokeWidth: 2
    };
    chart.Line(data, opts);
    legend = $("#legend");
    legend.empty();
    _ref = data.datasets;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      dataset = _ref[_i];
      li = $('<li><a style="color: ' + dataset.strokeColor + '" href="http://wikidata.org/wiki/User:' + dataset.name + '">' + dataset.name + '</a></li>');
      li.css({
        color: dataset.strokeColor
      });
      _results.push(legend.append(li));
    }
    return _results;
  };

  makeData = function(stats) {
    var color, data, datasets, hasData, i, labels, name, row, s, _i, _j, _len, _len1;

    datasets = [];
    for (i = _i = 0, _len = stats.length; _i < _len; i = ++_i) {
      s = stats[i];
      name = s.shift();
      labels = makeLabels(stats);
      data = [];
      hasData = false;
      for (_j = 0, _len1 = s.length; _j < _len1; _j++) {
        row = s[_j];
        if (row[1] > 0) {
          hasData = true;
        }
        data.push(row[1]);
      }
      color = colors[i];
      if (hasData) {
        datasets.push({
          name: name,
          strokeColor: color,
          data: data
        });
      }
    }
    return {
      labels: labels,
      datasets: datasets
    };
  };

  makeLabels = function(stats) {
    var count, d, labels, row, _i, _len, _ref;

    count = 0;
    labels = [];
    _ref = stats[1];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      row = _ref[_i];
      if (count % 7 === 0) {
        d = new Date(row[0] * 1000);
        labels.push(formatDate(d));
      } else {
        labels.push("");
      }
      count += 1;
    }
    return labels;
  };

  pad = function(n) {
    if (n < 10) {
      return '0' + n;
    } else {
      return n;
    }
  };

  formatDate = function(d) {
    return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate()) + ' ';
  };

  colors = ["blue", "blueviolet", "brown", "cadetblue", "chartreuse", "chocolate", "cornflowerblue", "crimson", "cyan", "darkblue", "darkcyan", "darkgoldenrod", "darkgray", "darkgreen", "darkkhaki", "darkmagenta", "darkolivegreen", "darkorange", "darkorchid", "darkred", "darksalmon", "darkseagreen", "darkturquoise", "darkviolet", "dodgerblue", "forestgreen", "fuchsia", "gainsboro", "gold", "goldenrod", "gray", "green", "greenyellow", "honeydew", "hotpink", "indianred", "indigo", "ivory", "khaki", "lavender", "lavenderblush", "lawngreen", "lemonchiffon", "lime", "limegreen", "linen", "magenta", "maroon", "mediumaquamarine", "mediumblue", "mediumorchid", "mediumpurple", "mediumseagreen", "mediumslateblue", "mediumspringgreen", "mediumturquoise", "mediumvioletred", "midnightblue", "mintcream", "mistyrose", "moccasin", "navajowhite", "navy", "oldlace", "olive", "olivedrab", "orange", "orangered", "orchid", "palegoldenrod", "palegreen", "paleturquoise", "palevioletred", "papayawhip", "peachpuff", "peru", "pink", "plum", "powderblue", "purple", "red", "rosybrown", "royalblue", "saddlebrown", "salmon", "sandybrown", "seagreen", "seashell", "sienna", "silver", "skyblue", "slateblue", "slategray", "snow", "springgreen", "steelblue", "tan", "teal", "thistle", "tomato", "turquoise", "violet", "wheat", "whitesmoke", "yellow", "yellowgreen"];

}).call(this);
